add_newline=false
command_timeout=1000

[shell]
fish_indicator = "ğŸŸ"
zsh_indicator = "zz"
disabled = true

[character]
success_symbol = "ğŸŒ¯"

[directory]
truncation_length=3
truncate_to_repo=false

[username]
show_always = false

[hostname]
ssh_only = true

[terraform]
disabled = true

[python]
disabled = false
pyenv_version_name = true

[conda]
ignore_base = false
format = "[$symbol$environment](dimmed green) "
disabled = false

[docker_context]
disabled = true

[aws]
disabled=true

[java]
disabled = true
