add_newline=false

[character]
symbol = "ğŸ•"

[directory]
truncation_length=3
truncate_to_repo=false

[username]
show_always = false

[hostname]
ssh_only = true

[terraform]
disabled = true

[python]
disabled = true

[conda]
disabled = false

[docker_context]
disabled = false

[aws]
disabled=true

[java]
disabled = true
